### ISSUE TITLE
Create Maven Artifact with DTOs for API Requests and Responses

### ISSUE THREAD

**Issue by MissakaI** [mosip/commons#1052]
**Is your feature request related to a problem? Please describe.**
While trying to build a Authentication Application for a partner I had the need to code the Requests and Response Models/DTOs. Since these are common to all applications using the API's I find it cumbersome to just copy paste the source files. And if the API's change then all the partners following similar procedure need to manually update their DTO's to match.

**Describe the solution you'd like**
Is there are a Java Library containing the Models/DTOs of the API Requests and Responses. Since these are mostly reusable across partners and other parties why don't we bundle all of these to a common package. I found these DTOs in `mosip-ref-impl` repository in some of the sample projects. Why don't we package these classes to a artifact that can be included via maven.

**Describe alternatives you've considered**
Currently I built the application by copying the DTO's and helpers from your `mosip-ref-impl`.

**Comment by urviljoshi** [comment]
@MissakaI Request and Response wrappers need not to be copied from anywhere they are already there in our [kernel-core](https://mvnrepository.com/artifact/io.mosip.kernel/kernel-core).
