### ISSUE TITLE
Starting Spring framework, get 404

### ISSUE THREAD

**Issue by ahmedelfaleh** [mosip/commons#39]
Hello,

I built and tried to run the spring framework by:
1. cloning commons
2. cd /kernel
3. cloning mosip-config
4. cp -a config-templates commons/kernel/kernel-config-server/config << without changing the variables yet.
5. vim kernel-config-server/src/main/resources/bootstrap.properties
6. uncommented the following
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=/home/mosip/mosip_project/mosip-config/config
7. cd $USER/project_dir/commons/kernel
8. mvn package
built successfully.
9. java -jar kernel-config-server/target/kernel-config-server-1.0.6-SNAPSHOT.jar 

curl -Iv localhost:51000/config/
give 404

I also tried it by spring.cloud.config.server.git.uri >> I provided forked git repo of mosip-config
and /config after changed it.

Every time gives my 404, I don't know if it's the meant config path or not, please advise.

**Comment by urviljoshi** [comment]
You are hitting the wrong url. Spring Cloud Config Server supports a URL with placeholders for the {application} and {profile} and {label} .

Please refer [https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html](url)
